
server:
  port: 8200
 
spring:
  datasource:
    username: root
    password: 654321
    url: jdbc:mysql://localhost:3319/tendays?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations:
    - file:D:\\DriveY\\neosoft2020\\webroot
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.hitstu.oa.hr.model, com.hitstu.oa.checkin.model, com.hitstu.oa.store.model, com.hitstu.oa.admin.model
 
#showSql
logging:
  level:
    com.hitstu.oa: debug
